# name: CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14'
#     - run: npm install
#     - run: npm test

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Updated to v3
    - name: Setup Node.js
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '20'  # Updated to Node.js 20
    - run: npm install
    - run: npm test
