name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ensure this is v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3  # Ensure this is v3
      with:
        node-version: '20'  # Explicitly set to Node.js 20
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
